### ISSUE TITLE
Clipboard error

### ISSUE THREAD

**Issue by xdelatour** [freemint/qed#8]
As reported by Philippe on the mailing list, a bug can occur with Qed and EmuTOS if there is no clipboard.

The following patch should fix this bug.

- Remove `s[strlen(s)-1] = EOS;` because the trailing backslash is **already** deleted by make_normalpath(clip_dir) (from [cflib](https://github.com/freemint/cflib/blob/16a82c2f54f92a388687ee05b1abcb746199aab9/fsnorm.c#L92-L94)) only if clipboard directory doesn't exist (if clipboard exists, a trailing backslash is added if it was missing)
- Check if there is a trailing backslash before concatenate "scrap.txt"

[clipbrd.c.patch.txt](https://github.com/freemint/qed/files/10797394/clipbrd.c.patch.txt)

**Comment by mikrosk** [comment]
Thank you Xavier, pushed.

**Comment by mikrosk** [comment]
Linking the discussion: https://sourceforge.net/p/freemint/mailman/freemint-discuss/thread/E083617B-C9A6-46D8-A3E8-489C96D880C4%40gmail.com/#msg37776976

There's still something weird going on with the clipboard handling in QED, I still see the message even when the folder does exist but I haven't investigated further.

**Comment by mikrosk** [comment]
Oh, this was a fun one. Very nicely underlined the need for real testing and avoiding guesswork. TL;DR version: both `Dcreate` and `Fattrib` reject paths with trailing backslash while FreeMiNT doesn't care.

In detail, there were several discrepancies:

- original code (before @xdelatour's patch) seemed to rely on the fact that `make_normalpath` always returns paths with trailing backslash
- however, as @xdelatour correctly pointed out in https://github.com/freemint/qed/issues/8#issue-1594066655, `make_normalpath` seemed to have the intention of removal the trailing backslash if the path didn't exist
- however, this worked only for paths which did **not** include the trailing backslash on input
- and on top of all that, `path_exists` was also failing with paths with trailing backslash

So...without @xdelatour's patch:

- the original bug report was while using EmuTOS. EmuTOS returns `C:\CLIPBRD` from `scrp_read`
  - `make_normalpath` would detect that the path doesn't exist and return the original `C:\CLIPBRD`
  - `s[strlen(s)-1] = EOS;` would transform `C:\CLIPBRD` to `C:\CLIPBR` and `Dcreate` would create it  (without displaying any message box)
  - by the next launch `make_normalpath` would again detect that `C:\CLIPBRD` doesn't exist and go on to create `C:\CLIPBR` which now does exist and that would display the message box with error

Obviously, all that's needed is @xdelatour's patch to avoid the losing the last `D` character, right?

- ok... EmuTOS still returns `C:\CLIPBRD` from `scrp_read`
  - `make_normalpath` would detect that the path doesn't exist and return the original `C:\CLIPBRD`
  - `Dcreate` would create `C:\CLIPBRD` ... awesome!
  - by the next launch `make_normalpath` would again detect that `C:\CLIPBRD` doesn't exist and would go on to create `C:\CLIPBRD` which now does exist and that would display the message box with error ... wait, what?

Why would it detect that `C:\CLIPBRD` doesn't exist? Because `make_normalpath`'s [code](https://github.com/freemint/cflib/blob/16a82c2f54f92a388687ee05b1abcb746199aab9/fsnorm.c#L85-L90) artifically appends `\` to the path when it exists! And ... `path_exists` using `Fattrib` doesn't like this at all.

Ok, let's fix `make_normalpath` in CF-Lib so it calls `path_exists` _before_ appending the `\`. This does the trick however...

- then you run QED in TOS. TOS returns `C:\CLIPBRD\` from `scrp_read` (note the trailing slash)
  - `make_normalpath` would detect that the path doesn't exist and return the original `C:\CLIPBRD\`
  - as we are now using @xdelatour's patch, the path passed to `Dcreate` is not shortened (i.e. with the trailing backslash) and ... it fails! That was the true reason behind that code which was now removed!
  - there is no second step,  `C:\CLIPBRD` is never created!

So... now we have the complete picture. We have to support also paths with trailing backslash. To do this, we have to patch both `path_exists` and `make_normalpath`:
- `path_exists` now doesn't fail with paths with trailing backslash on input
- `make_normalpath` always returns paths with trailing backslash
- now, @xdelatour's patch is doing just damage => revert

You might ask "should `make_normalpath` really behave like this? [I believe so](https://github.com/freemint/cflib/commit/2ac3e85b126f755132e1c3725a480a03038c7d2c).

And one last thing... why did all of this happen only in (Emu)TOS you ask? Well, because FreeMiNT is true to the [Robusness principle](https://en.wikipedia.org/wiki/Robustness_principle): _be conservative in what you do, be liberal in what you accept from others_. In other words, it doesn't care whether `Dcreate` or `Fattrib` have trailing backslash on input or not.

**Comment by th-otto** [comment]
Nice analysis. Hopefully fixed now for all cases ;)
